version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      # CHANGE_ME: DB user - you can change but keep consistent with .env
      POSTGRES_USER: pod_user
      # CHANGE_ME: DB password - change to a secure password
      POSTGRES_PASSWORD: Sammsa12
      POSTGRES_DB: pod_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pod_user -d pod_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb_app
    ports:
      - "8080:8080"
    environment:
      # Database connection for NocoDB (internal Docker network host = service name 'postgres')
      # Use both POSTGRES_DB_URL and NC_DB (some images look for POSTGRES_DB_URL)
      POSTGRES_DB_URL: "postgresql://pod_user:Sammsa12@postgres:5432/pod_db?sslmode=disable"
      NC_DB: "postgresql://pod_user:Sammsa12@postgres:5432/pod_db?sslmode=disable"
      NC_BASE_URL: "http://localhost:8080"  # CHANGE_ME if exposing differently
    volumes:
      - nocodb_data:/usr/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: Admin            # CHANGE_ME: n8n login user
      N8N_BASIC_AUTH_PASSWORD: Admihaen!    # CHANGE_ME: n8n login password
      GENERIC_TIMEZONE: Asia/Manila
      N8N_HOST: n8n.astagrsm.qzz.io
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://n8n.astagrsm.qzz.io/
      N8N_PORT: 5678
      N8N_DISABLE_PRODUCTION_MAIN_PROCESS: "true"
      N8N_PERSONALIZATION_ENABLED: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_app
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  nocodb_data:
  n8n_data:
  qdrant_storage:
  ollama_storage: