// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxabhvllxmblwvrcmgfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4YWJodmxseG1ibHd2cmNtZ2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTI2ODIsImV4cCI6MjA3NDQ2ODY4Mn0.u8ajYy35YSckKWTwGKkMka0b9B_w-5_7NuSUPmage1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});