// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsxrldwvastkwwtcmwiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeHJsZHd2YXN0a3d3dGNtd2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzQ3OTgsImV4cCI6MjA3NDUxMDc5OH0.YFtOBq4wIJcUih-ufPhVpp79ibHTmBHAZFL0mCS7EvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});